[project]
name = "k4-3a-e403-phronesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nthanhwork", email = "nthaianh.work@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pip>=26.2.1",
]

[project.scripts]
k4-3a-e403-phronesis = "k4_3a_e403_phronesis:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
